Azure: Network Error on clicking Login button in Admin Login Page
Error: On clicking reports page , filling email and password in Admin Login page and clicking Login raises error: Network error.

Fix: Added REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }} to .gitnub/workflows/deploy-frontend.yml file.

This is because backend is not reached in Azure.